showoff/frontend/forms.py
# Imports {{{
from wtforms import TextField, PasswordField, validators
from flask.ext.wtf import Form
# }}}

class LoginForm(Form):
    username = TextField('Username', validators=[validators.Required(message='Username is required.')])
    password = PasswordField('Password', validators=[validators.Required(message='Password is required.')])

showoff/frontend/controllers.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Showoff - Webbased photo album software

Copyright (c) 2010-2014 by Jochem Kossen <jochem@jkossen.nl>

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

   1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials provided
   with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from flask import Blueprint, current_app, safe_join, Flask, abort, \
    render_template, send_from_directory, request, redirect, session, \
    url_for
from showoff.lib import Show, Image, CacheManager, ExifManager
from .lib.authentication import login_required, authenticate
from .lib.page import get_paginator, render_themed
from .forms import LoginForm
import os

frontend = Blueprint('frontend', __name__, template_folder='templates')


@frontend.route('/login/<album>', methods=['GET', 'POST'])
def login(album):
    if request.method == 'POST':
        if authenticate(album):
            if 'next_url' in session \
               and session['next_url'] is not None \
               and session['next_url'] != url_for('.login', album=album):
                next_url = session['next_url']
                session.pop('next_url', None)
                return redirect(next_url)
            return redirect(url_for('.show_album', album=album))
    return render_themed('login.html', album=album, form=LoginForm())


@frontend.route('/static_files/<path:filename>')
def static_files(filename):
    """Send static files such as style sheets, JavaScript, etc."""
    static_path = os.path.join(frontend.root_path,
                               'templates',
                               current_app.config['THEME'], 'static')
    return send_from_directory(static_path, filename)


@frontend.route('/image/<album>/<filename>/full/', defaults={'size': 'full'})
@frontend.route('/image/<album>/<filename>/<int:size>/')
@login_required
def get_image(album, filename, size="full"):
    image = Image(album, filename, current_app.config)
    cache = CacheManager(image, current_app.config)
    return send_from_directory(*cache.get(size))


@frontend.route('/page/<album>/<filename>.html')
@login_required
def image_page(album, filename, template='image'):
    image = Image(album, filename, current_app.config)
    show = Show(album, current_app.config, session)
    exif_manager = ExifManager(image)
    exif_array = exif_manager.get_exif()

    return render_themed(template + '.html', album=album, filename=filename,
                         exif=exif_array, show=show)


@frontend.route('/list/<album>/<template>/<int:page>.html')
@frontend.route('/list/<album>/<int:page>.html')
@login_required
def list_album(album, page, template='list'):
    if template in current_app.config['FRONTEND_LIST_TEMPLATES']:
        show = Show(album, current_app.config, session)
        paginator = get_paginator(album, page, 'frontend.list_album', template)
        return render_themed(template + '.html',
                             album=album,
                             show=show,
                             files=paginator.entries,
                             paginator=paginator,
                             page=page)
    else:
        abort(404)


@frontend.route('/fullshow/<album>/<template>.html')
@login_required
def show_nonpaginated(album, template='grid_full'):
    show = Show(album, current_app.config, session)

    if len(show.data['files']) == 0:
        abort(404)

    files = show.data['files']
    return render_themed(template + '.html', album=album, files=files)


@frontend.route('/slideshow/<album>/<int:page>.html')
@login_required
def show_slideshow(album, page):
    paginator = get_paginator(album,
                              page,
                              'frontend.show_slideshow',
                              'slideshow.html')
    return render_themed('slideshow.html',
                         album=album,
                         files=p.entries,
                         paginator=p,
                         page=page)


@frontend.route('/<album>.html')
@login_required
def show_album(album):
    """Render first page of album"""
    return list_album(album, 1)


@frontend.route('/')
def show_index():
    dir_list = os.listdir(current_app.config['ALBUMS_DIR'])
    full_album_list = [os.path.basename(album) for album in dir_list]
    shows = {}

    for album in full_album_list:
        show = Show(album, current_app.config, session)
        if show.is_enabled:
            shows[album] = show

    album_list = shows.keys()
    album_list.sort(reverse=True)

    return render_themed('index.html', albums=album_list, shows=shows)

showoff/frontend/templates/v2/_paginator.html
<div class="paginator">
    {%- if paginator.has_previous %}
    Page: <a href="{{ url_for(**paginator.first) }}">&laquo; first</a>
    <a href="{{ url_for(**paginator.previous) }}">&lsaquo; prev</a>
    {%- else %}
    Page: &laquo; first
    <span class="inactive"> &lsaquo; prev</span>
    {% endif %}
    | {{ paginator.page }} /
    {% if paginator.has_next %}
    <a href="{{ url_for(**paginator.last) }}">{{ paginator.pages }}</a> |
    {% else %}
    {{ paginator.pages }} |
    {% endif %}
    {% if paginator.has_next %}
    <a href="{{ url_for(**paginator.next) }}">next &rsaquo;</a>
    <a href="{{ url_for(**paginator.last) }}">last &raquo;</a>
    {%- else %}
    <span class="inactive">next &rsaquo;</span>
    <span class="inactive">last &raquo;</span>
    {% endif %}
</div>

showoff/frontend/templates/v2/image.html
{% extends "v2/layout.html" %}

{% block title %}{{ config.TITLE }} - {{ filename }}{% endblock %}

{% block body %}
<div class="container">
<h1><a href="{{ url_for('frontend.show_album', album=album) }}">{{ album }}</a></h1>
<h2>{{ filename }}</h2>
{% for message in get_flashed_messages() %}
<div class="flash">{{ message }}</div>
{% endfor %}

<p>Available image sizes:
{% for size in config.ALLOWED_SIZES %}
{% if size != 'full' %}
<a href="{{ url_for('frontend.get_image', album=album, size=size, filename=filename) }}">{{ size }}</a>
{% else %}
<a href="{{ url_for('frontend.get_image', album=album, filename=filename, size='full') }}">{{ size }}</a>
{% endif %}
{% if not loop.last %}
|
{% endif %}
{% endfor %}
</p>

<div class="">
<img src="{{ url_for('frontend.get_image', album=album, filename=filename, size=config.IMAGE_SIZE) }}" alt="{{ filename }}" />
</div>

<div class="panel panel-default">
<div class="panel-heading">Exif information</div>
<table class="table">
    {% for key in exif.keys() %}
    <tr><td>{{ key }}</td><td> {{ exif[key] }}</td></tr>
    {% endfor %}
</table>

</div>
{% endblock %}

showoff/frontend/templates/v2/index.html
{% extends "v2/layout.html" %}

{% block body %}
<div class="container">
<div class="page-header">
<h1><a href="{{ url_for('frontend.show_index') }}">{{ config.TITLE }}</a></h1>
</div>

<h2>Available photo albums:</h2>

{% for album in albums %}
<div class="media">
    <a class="pull-left" href="{{ url_for('frontend.show_album', album=album) }}">
        <img src="{{ url_for('frontend.get_image', album=album, size=400, filename=shows[album].data['files'][0]) }}" />
    </a>
    <div class="media-body">
        <h4 class="media-heading"><a href="{{ url_for('frontend.show_album', album=album) }}">{{ album }}</a> ({{ shows[album].nr_of_items }} photos)</h4>
    </div>
</div>
{% endfor %}

</div>
{% endblock %}

showoff/frontend/templates/v2/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{{ config.TITLE }}{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('frontend.static_files', filename='bootstrap/css/bootstrap.min.css') }}" type="text/css" />
        <link rel="stylesheet" href="{{ url_for('frontend.static_files', filename='style.css') }}" />
        {% block posthead %}{% endblock %}
        {% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url_for('frontend.show_index') }}">{{ config.TITLE }}</a>{% block extratitle %}{% endblock %}
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        {% block extranav %}{% endblock %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block body %}
        {% endblock %}

        <div class="container">
            <div class="footer">
                <hr>
                copyright &copy; 2014 by Jochem Kossen
            </div>
        </div>

        <script type="text/javascript" src="{{ url_for('frontend.static_files', filename='jquery.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('frontend.static_files', filename='bootstrap/js/bootstrap.min.js') }}"></script>
        {% block postfooter %}{% endblock %}
    </body>
</html>

showoff/frontend/templates/v2/list.html
{% extends "v2/layout.html" %}

{% block title %}{{ album }} page {{ paginator.page }} of {{ paginator.pages }}{% endblock %}

{% block posthead %}
<link rel="stylesheet" href="{{ url_for('frontend.static_files', filename='swipebox/src/css/swipebox.css') }}" type="text/css" />
{% endblock %}


{% block extranav %}
{% endblock %}

{% block extratitle %}<a class="navbar-brand" href="#">/ {{ album }}</a>{% endblock %}

{% block body %}
<div class="container">
    <div class="page-header">
        {% include "v2/_paginator.html" %}
        <h1><a href="{{ url_for('frontend.show_album', album=album) }}">{{ album }}</a><small> ({{ paginator.count }} photos)</small></h1>
    </div>


    <h2>{{ config.THUMBNAILS_PER_PAGE }} photos per page. This is page {{ paginator.page }} of {{ paginator.pages }}</h2>

    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor %}

    {% set rows = config.THUMBNAILS_PER_PAGE / 2 %}
    {% for f in files | slice(rows|int) %}
    <div class="row">
        
        {% for filename in f %}
        <div class="col-md-6 navigation-container">
            <div class="thumbnail">
                <div class="btn-group-vertical" style="float:right;">
                    <a class="btn" href="{{ url_for('frontend.image_page', album=album, filename=filename) }}" title="more information and sizes"><span class="glyphicon glyphicon-info-sign"></span></a>
                    <a class="btn" href="{{ url_for('frontend.get_image', album=album, filename=filename, size='full') }}" title="Download full-size image"><span class="glyphicon glyphicon-floppy-disk"></span></a>
                </div>
                <a class="swipebox thumb" href="{{ url_for('frontend.get_image', album=album, filename=filename, size='full') }}" title="{{ filename }}">
                    <img src="{{ url_for('frontend.get_image', album=album, filename=filename, size=config.THUMBNAIL_SIZE) }}" alt="{{ filename }}"/>
                </a>
                <div style="clear:both;"></div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

    <div class="content">
        <div class="slideshow-container">
            <div id="loading" class="loader"></div>
            <div id="slideshow" class="slideshow"></div>
        </div>
        <div id="caption" class="caption-container">
            <div class="photo-index"></div>
        </div>
    </div>
    {% include "v2/_paginator.html" %}
</div>
{% endblock %}

{% block postfooter %}
<script type="text/javascript" src="{{ url_for('frontend.static_files', filename='swipebox/src/js/jquery.swipebox.js') }}"></script>
<script type="text/javascript">
    ;( function( $ ) {

	$( '.swipebox' ).swipebox();

    } )( jQuery );
</script>
{% endblock %}

showoff/frontend/templates/v2/login.html
{% extends "v2/layout.html" %}
{% block extratitle %}Login - {% endblock %}

{% block body %}
<div class="container">
    <h1>Login</h1>
    <h3>This album requires a valid user</h3>
    <form class="form-signin" action="{{ url_for('frontend.login', album=album) }}" method=post>
        {{ form.csrf_token }}
        {{ form.username.label }}
        {{ form.username }}

        {% if form.username.errors %}
        <ul class="errors">
            {% for error in form.username.errors %}<li>{{ error }}</li>{% endfor %}
        </ul>
        {% endif %}

        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
        <ul class="errors">
            {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
        </ul>
        {% endif %}

        <button class="btn btn-lg btn-primary" type="submit"><span class="glyphicon glyphicon-log-in"></span> login</button>
    </form>
</div>
{% endblock %}