showoff/admin/controllers.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Showoff - Webbased photo album software

Copyright (c) 2010-2014 by Jochem Kossen <jochem@jkossen.nl>

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

   1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials provided
   with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""

from flask import Blueprint, current_app, render_template, \
    send_from_directory, url_for, redirect, jsonify, request, \
    session
from showoff.lib import Show, Image, CacheManager, ExifManager
from showoff.admin.lib import ImageModifier
from showoff.admin.lib.page import _paginated_overview

import os
import re

admin = Blueprint('admin', __name__, template_folder='templates')


def render_themed(template, **options):
    template_path = os.path.join(current_app.config['ADMIN_THEME'], template)
    return render_template(template_path, **options)

def get_image_cache(album, filename):
    image = Image(album, filename, current_app.config)
    cache = CacheManager(image, current_app.config)

    return image, cache

@admin.route('/static_files/<path:filename>')
def static_files(filename):
    """Send static files such as style sheets, JavaScript, etc."""
    static_path = os.path.join(admin.root_path,
                               'templates',
                               current_app.config['ADMIN_THEME'],
                               'static')
    return send_from_directory(static_path, filename)


@admin.route('/<album>/image/<filename>/<int:size>/')
def show_image(album, filename, size=None):
    image, cache = get_image_cache(album, filename)
    return send_from_directory(*cache.get(size))


@admin.route('/<album>/image/<filename>/full/')
def show_image_full(album, filename):
    return show_image(album, filename, 'full')


@admin.route('/<album>/show/<filename>')
def image_page(album, filename):
    show = Show(album, current_app.config, session)
    image = Image(album, filename, current_app.config)
    exif_manager = ExifManager(image)
    exif_array = exif_manager.get()
    if exif_array is None:
        exif_array = {}
    return render_themed('image.html', album=album, filename=filename,
                         exif=exif_array, show=show)


@admin.route('/<album>/rotate_exif/')
def rotate_url():
    # dummy
    pass


@admin.route('/<album>/list/<template>/<int:page>/')
@admin.route('/<album>/list/<int:page>/')
def list_album(album, page, template='grid'):
    show = Show(album, current_app.config, session)
    ext = re.compile(".(jpg|png|gif|bmp)$", re.IGNORECASE)

    album_dir = os.path.join(current_app.config['ALBUMS_DIR'], album)
    all_files = [f for f in os.listdir(album_dir) if ext.search(f)]
    all_files.sort()

    if show.get_setting('reverse') == 'yes':
        all_files.reverse()

    paginator = _paginated_overview(album, page, 'admin.list_album', template)
    return render_themed(template + '.html',
                         album=album,
                         show=show,
                         files=paginator.entries,
                         paginator=paginator,
                         page=page,
                         all_files=all_files)


@admin.route('/<album>/')
def show_album(album):
    return list_album(album, 1)


@admin.route('/')
def show_index():
    dir_list = os.listdir(current_app.config['ALBUMS_DIR'])
    album_list = [os.path.basename(album) for album in dir_list]
    album_list.sort(reverse=True)
    return render_themed('index.html', albums=album_list)


@admin.route('/<album>/<filename>/rotate/<int:steps>/')
def image_rotate(album, filename, steps=1):
    image = Image(album, filename, current_app.config)
    image_modifier = ImageModifier(image)
    image_modifier.rotate(steps)
    return jsonify(result='OK')


@admin.route('/<album>/rotate_exif/<filename>/')
def exif_rotate_image(album, filename):
    image = Image(album, filename, current_app.config)
    image_modifier = ImageModifier(image)
    image_modifier.rotate_exif()
    return jsonify(result='OK')


@admin.route('/<album>/<filename>/toggle_publish/')
def toggle_publish_image(album, filename):
    """Toggle publish image"""
    show = Show(album, current_app.config, session)
    try:
        show.toggle_image(filename).save()
    except:
        return jsonify(result='Failed')

    return jsonify(result='OK')

@admin.route('/<album>/add_image_to_show/<filename>/')
def add_image_to_show(album, filename):
    """Add an image to the show"""
    show = Show(album, current_app.config, session)
    try:
        show.add_image(filename).save()
    except:
        return jsonify(result='Failed')

    return jsonify(result='OK')


@admin.route('/<album>/remove_image_from_show/<filename>/')
def remove_image_from_show(album, filename):
    """Remove an image from the show"""
    show = Show(album, current_app.config, session)

    try:
        show.remove_image(filename).save()
    except:
        return jsonify(result='Failed')

    return jsonify(result='OK')

@admin.route('/<album>/sort_by_exifdate/')
def sort_show_by_exifdate(album):
    """Sort the show by exif datetime """
    show = Show(album, current_app.config, session)
    show.sort_by_exif_datetime().save()
    return goback(True)

@admin.route('/<album>/sort_by_filename/')
def sort_show_by_filename(album):
    """Sort the show by filename """
    show = Show(album, current_app.config, session)
    show.sort_by_filename().save()
    return goback(True)

@admin.route('/<album>/edit_users/')
def show_edit_users(album):
    show = Show(album, current_app.config, session)
    users = show.data['users']
    return render_themed('edit_users.html',
                         album=album,
                         show=show,
                         users=users)


@admin.route('/<album>/add_all/')
def add_all_images_to_show(album):
    show = Show(album, current_app.config, session)
    show.add_all_images().save()
    return goback(True)


@admin.route('/<album>/set/<setting>/<value>/')
def show_change_setting(album, setting, value):
    show = Show(album, current_app.config, session)
    try:
        show.change_setting(setting, value).save()
    except:
        return jsonify(result='Failed')
    return jsonify(result='OK')

@admin.route('/<album>/change_password/', methods=['POST'])
def show_change_password(album):
    if request.method == 'POST':
        show = Show(album, current_app.config, session)
        username = request.form['username']
        password = request.form['password']
        show.set_user(username, current_app.config['SECRET_KEY'], password).save()
        return goback(True)


@admin.route('/<album>/remove_user/<username>/')
def show_remove_user(album, username):
    show = Show(album, current_app.config, session)
    show.remove_user(username).save()
    return jsonify(result='OK')

def goback(is_ok):
    if is_ok:
        return redirect(request.referrer or url_for('.index'))
    else:
        return jsonify(result='Failed')

showoff/admin/lib/__init__.py
from image_modifier import ImageModifier

showoff/admin/templates/v2/_paginator.html
<div class="paginator">
    {%- if paginator.has_previous %}
    Page: <a href="{{ url_for(**paginator.first) }}">&laquo; first</a>
    <a href="{{ url_for(**paginator.previous) }}">&lsaquo; prev</a>
    {%- else %}
    Page: &laquo; first
    <span class="inactive"> &lsaquo; prev</span>
    {% endif %}
    | {{ paginator.page }} /
    {% if paginator.has_next %}
    <a href="{{ url_for(**paginator.last) }}">{{ paginator.pages }}</a> |
    {% else %}
    {{ paginator.pages }} |
    {% endif %}
    {% if paginator.has_next %}
    <a href="{{ url_for(**paginator.next) }}">next &rsaquo;</a>
    <a href="{{ url_for(**paginator.last) }}">last &raquo;</a>
    {%- else %}
    <span class="inactive">next &rsaquo;</span>
    <span class="inactive">last &raquo;</span>
    {% endif %}
</div>

showoff/admin/templates/v2/edit_users.html
{% extends "v2/layout.html" %}

{% block title %}{{ album }} - edit users{% endblock %}

{% block extrahead %}
<script src="{{ url_for('admin.static_files', filename='jquery.js') }}"></script>
<script src="{{ url_for('admin.static_files', filename='showoffadmin.js') }}"></script>
<script>
    show_toggle_require_auth = function(element, value) {
        $(element).html('please wait ...');
        url_yes = '{{ url_for('admin.show_change_setting', album=album, setting='require_authentication', value='yes') }}';
        url_no = '{{ url_for('admin.show_change_setting', album=album, setting='require_authentication', value='no') }}';
        url = (value == 'yes') ? url_yes : url_no;
        result = $.getJSON(url, false, function() {
            img = (value == 'yes') ? '{{ url_for('admin.static_files', filename='on.png') }}' : '{{ url_for('admin.static_files', filename='off.png') }}';
            new_text = '<img src="' + img + '">';
            new_value = (value == 'yes') ? 'no' : 'yes';
            done_html = '<a href="#" onclick=\'return show_toggle_require_auth("' + element + '", "' + new_value + '");\'>' + new_text + '</a>';
            $(element).html(done_html);
        });
        return false;
    }
</script>
{% endblock %}

{% block body %}
<h1><a href="{{ url_for('admin.show_album', album=album) }}">{{ album }}</a></h1>

require authentication:
<span id="toggle_show">
    {% if show.get_setting('require_authentication') == 'yes' %}
    <a href="#" onclick="return show_toggle_require_auth('#toggle_show', 'no')"><img src="{{ url_for('admin.static_files', filename='on.png') }}" alt="disable"></a>
    {% else %}
    <a href="#" onclick="return show_toggle_require_auth('#toggle_show', 'yes')"><img src="{{ url_for('admin.static_files', filename='off.png') }}" alt="disable"></a>
    {% endif %}
</span>

{% for message in get_flashed_messages() %}
<div class="flash">{{ message }}</div>
{% endfor %}

<h3>Add new user</h3>
<form role="form" class="form-horizontal" action="{{ url_for('admin.show_change_password', album=album) }}" method="POST">
    <div class="form-group">
        <label for="new-user-username" class="col-sm-2 control-label">Username</label>
        <div class="col-sm-10">
            <input class="form-control" id="new-user-username" type="text" name="username" placeholder="Username">
        </div>
    </div>

    <div class="form-group">
        <label for="new-user-password" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
            <input class="form-control" id="new-user-password" type="password" name="password" placeholder="Password">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">    
            <button type="submit" class="btn btn-primary">save</button>
        </div>
    </div>
</form>

<h3>Existing users</h3>
{% for user in users %}
<div id="user-{{ loop.index }}">
    <form role="form" class="form-horizontal" action="{{ url_for('admin.show_change_password', album=album) }}" method="POST">
        <input class="form-control" type="hidden" name="username" value="{{ user }}">

        <div class="form-group">
            <label for="user-password-{{ user }}" class="col-sm-3 control-label" style="text-align:left;">{{ user }}</label>
            <div class="col-sm-7">
                <input class="form-control" id="user-password-{{ user }}" type="password" name="password" placeholder="Password">
            </div>
            <div class="col-sm-1">    
                <button type="submit" class="btn btn-primary">save</button>
            </div>
            <div class="col-sm-1">    
                <button type="button" id="delete-user-{{ user }}" data-username="{{ user }}" data-index="{{ loop.index }}" class="btn btn-danger delete-user">Delete user</button>
            </div>
        </div>
    </form>
</div>
<!--a href="{{ url_for('admin.show_remove_user', album=album, username=user) }}">Delete user</a-->
{% endfor %}

<script>
    $(document).ready(function() {
        var cfg = {
            'base_url': '{{ url_for('admin.show_index') }}',
            'album': '{{ album }}'
        };

        var images = [ ];

        SHOWOFFADMIN.init(cfg, images);
        SHOWOFFADMIN.init_edit_users();
});
</script>
{% endblock %}

showoff/admin/templates/v2/grid.html
{% extends "v2/layout.html" %}

{% block title %}{{ album }} - grid view{% endblock %}

{% block extrahead %}
<script src="{{ url_for('admin.static_files', filename='jquery.js') }}"></script>
<script src="{{ url_for('admin.static_files', filename='jquery.blockUI.js') }}"></script>
<script src="{{ url_for('admin.static_files', filename='showoffadmin.js') }}"></script>
{% endblock %}

{% block body %}
<h1><a href="{{ url_for('admin.show_album', album=album) }}">{{ album }}</a></h1>
{% for message in get_flashed_messages() %}
<div class="flash">{{ message }}</div>
{% endfor %}

<div class="well">
    <div class="row">
        <div class="col-md-6">
            <ul>
                <li>authentication required:
                    <span id="toggle_show">
                        <a href="#" class="toggle-bool" data-setting="require_authentication" data-value="{{ show.get_setting('require_authentication') }}"></a>
                    </span>
                </li>
                <li>show album in reverse order:
                    <span id="toggle_reverse">
                        <a href="#" class="toggle-bool" data-setting="reverse" data-value="{{ show.get_setting('reverse') }}"></a>
                    </span>
                </li>
		        <li><a href="{{ url_for('admin.show_edit_users', album=album) }}">Edit users</a></li>
                <li><a id="rotate-all-images" href="#">Rotate all images based on exif info</a></li>
            </ul>
        </div>
        <div class="col-md-6">
            <ul>
                <li><a href="{{ url_for('admin.add_all_images_to_show', album=album) }}">Add all images to show</a></li>
                <li><a href="{{ url_for('admin.sort_show_by_exifdate', album=album) }}">Sort show by exifdate</a></li>
                <li><a href="{{ url_for('admin.sort_show_by_filename', album=album) }}">Sort show by filename</a></li>
                <li><a href="{{ url_for('admin.show_index') }}">Other albums</a><br>
            </ul>
        </div>
    </div>
</div>

{% include "v2/_paginator.html" %}
<div class="clearfix"></div>
<hr>

<div class="grid-container">
    {% for filename in files %}
    <div class="grid-item col-md-4{% if filename in show.data['files'] %} published{% endif %}">
        <a class="grid-item-image"
           href="{{ url_for('admin.image_page', album=album, filename=filename) }}" title="{{ filename }}">
            <img id="img-{{ loop.index }}" src="{{ url_for('admin.show_image', album=album, filename=filename, size=config.GRID_SIZE) }}" alt="{{ filename }}" data-filename="{{ filename }}">
        </a>
        <div>publish:
            <a href="#" class="toggle-publish" data-filename="{{ filename }}" data-value="{% if filename in show.data['files'] %}yes{% else %}no{% endif %}"></a>
        </div>
        <div>rotate:
            <a href="#" class="rotate" data-steps="1" data-index="{{ loop.index }}">¼</a> &raquo;
            <a href="#" class="rotate" data-steps="2" data-index="{{ loop.index }}">½</a> &raquo;
            <a href="#" class="rotate" data-steps="3" data-index="{{ loop.index }}">¾</a>
        </div>
    </div>
    {% endfor %}
</div>

<div class="clearfix"></div>
{% include "v2/_paginator.html" %}

<div id="footer"><hr>&copy; 2010-2014 Jochem Kossen</div>

<script>
    $(document).ready(function() {
    var cfg = {
    'base_url': '{{ url_for('admin.show_index') }}',
    'album': '{{ album }}'
    };

    var images = [ {% for filename in all_files %}'{{ filename }}'{% if not loop.last %}, {% endif %}{% endfor %} ];

    SHOWOFFADMIN.init(cfg, images);
    });
</script>
{% endblock %}

showoff/admin/templates/v2/image.html
{% extends "v2/layout.html" %}

{% block title %}{{ config.TITLE }} - {{ filename }}{% endblock %}

{% block body %}
<h1><a href="{{ url_for('admin.show_album', album=album) }}">{{ album }}</a></h1>
<h2>{{ filename }}</h2>
{% for message in get_flashed_messages() %}
<div class="flash">{{ message }}</div>
{% endfor %}

<p>Download image in sizes:
{% for size in config.ALLOWED_SIZES %}
{% if size != 'full' %}
<a href="{{ url_for('admin.show_image', album=album, size=size, filename=filename) }}">{{ size }}</a>
{% else %}
<a href="{{ url_for('admin.show_image_full', album=album, filename=filename) }}">{{ size }}</a>
{% endif %}
{% if not loop.last %}
|
{% endif %}
{% endfor %}
<br />Actions:
{% if filename in show.data['files'] %}
<a href="{{ url_for('admin.remove_image_from_show', album=album, filename=filename) }}">remove from show</a>
{% else %}
<a href="{{ url_for('admin.add_image_to_show', album=album, filename=filename) }}">add to show</a>
{% endif %}
rotate clockwise:
<a href="#" onclick='rotate("{{ url_for('admin.image_rotate', album=album, filename=filename, steps=1) }}");return false;'>¼</a> &raquo;
<a href="#" onclick='rotate("{{ url_for('admin.image_rotate', album=album, filename=filename, steps=2) }}");return false;'>½</a> &raquo;
<a href="#" onclick='rotate("{{ url_for('admin.image_rotate', album=album, filename=filename, steps=3) }}");return false;'>¾</a>
</p>

<img src="{{ url_for('admin.show_image', album=album, filename=filename, size=config.IMAGE_SIZE) }}" alt="{{ filename }}" />

<h3>Exif information</h3>
<table>
{% for key in exif.keys() %}
<tr><td>{{ key }}</td><td> {{ exif[key] }}</td></tr>
{% endfor %}
</table>

<script type="text/javascript">
rotate = function(url) {
    $.blockUI({ message: '<h1>Rotating image ...</h1>'});
    $.ajax({
        url: url,
        context: document.body,
        success: function() {
            window.location.reload();
        }
        });
}
</script>

{% endblock %}

showoff/admin/templates/v2/index.html
{% extends "v2/layout.html" %}

{% block body %}
<h1><a href="{{ url_for('admin.show_index') }}">{{ config.TITLE }}</a></h1>

<h2>Available photo albums:</h2>

<ul>
{% for album in albums %}
<li><a href="{{ url_for('admin.show_album', album=album) }}">{{ album }}</a></li>
{% endfor %}
</ul>
{% endblock %}

showoff/admin/templates/v2/layout.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{{ config.TITLE }}{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('admin.static_files', filename='bootstrap/css/bootstrap.min.css') }}" type="text/css" />
        <link rel="stylesheet" href="{{ url_for('admin.static_files', filename='style.css') }}" />
        {%block extrahead %}{% endblock %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url_for('admin.show_index') }}">{{ config.TITLE }}</a>{% block extratitle %}{% endblock %}
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        {% block extranav %}{% endblock %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            {% block body %}{% endblock %}
        </div>
    </body>
</html>